### ISSUE TITLE
System.Exception: Key 'gamelogo' already exists in object.

### ISSUE THREAD

**Issue by Bluscream** [shravan2x/Gameloop.Vdf#21]
```
08:10:21.4855 | ERROR | System.Exception: Key 'gamelogo' already exists in object.
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.HandleValueDuplicateKey(JObject baseObj, VProperty prop, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VObject obj, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VToken tok, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VProperty prop, VdfJsonConversionSettings settings)
   at GModMountManager.Classes.Game..ctor(DirectoryInfo gameDir) in C:\Users\blusc\source\repos\GMod Mount Manager\Classes\GameInfo.cs:line 47
```

Is this related to #8?

**Comment by shravan2x** [comment]
Since I'm unable to repro this issue with the gameinfo.txt file you provided me with earlier, I'll assume it's a different file.

As you already found, `ObjectDuplicateKeyHandling` and `ValueDuplicateKeyHandling` are the settings used to deal with duplicate keys when converting to JSON. This is required because JSON doesn't allow duplicate keys, unlike VDF.

**Important note**: If you're converting to JSON so you can deserialize to a model, note that using the `Ignore` setting will cause permanent loss of data. This is because all duplicate keys will be discarded (i.e. _Ignored_).

**Comment by Bluscream** [comment]
In this case i am okay with the loss of data, the game only uses the first one of each entries anyway.

**Comment by shravan2x** [comment]
Then `Ignore` should work fine. I've also updated the `Gameloop.Vdf.JsonConverter` README to include [documentation on handling duplicate keys](https://github.com/shravan2x/Gameloop.Vdf.JsonConverter#handling-duplicate-keys-when-converting-to-json).
